// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jckfoqqpncxxeqtflhiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impja2ZvcXFwbmN4eGVxdGZsaGl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNDIzNTQsImV4cCI6MjA3MzYxODM1NH0.ga9CKxuF2ntkvDyaYZdYcQ7ln6r0L-83bFNw3X08wfM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});